kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.tooling.parallel=true

tor.bundle.version=15.0.23
tor.sha256.windows.x86_64=231dad6b9cb401a54c260db7046965ef04e4f72ff071b140d423fb5da281ab1e
tor.sha256.linux.x86_64=08d49de27f542b8f73e2014e064d8320562b5d20019c03d4725c5a5249d97985
tor.sha256.macos.x86_64=be1be1cb13cd093713f02a0beade0d2471b61119011bfeb0efc08353eadf2e4e
tor.sha256.macos.aarch64=e8ea3f667c83309abad34280f0f9e1cfae52843da6b8db111ca15d6221051db5
tor.sha256.android.aarch64=ed4bc23065ee10f68efcdae63ea318ffa4b02b04ba00f13a3f59f8e3832fdfad
tor.sha256.android.armv7=2bf7d66307db90fc3f76ca0d412723de9e37755454cbeb22d806a3b4c9c22595
tor.sha256.android.x86_64=88c8c6fe3d11db84bb6ea90bae801419f39b4650aac80baeff38528a82d3fd91
tor.sha256.android.x86=8718d85a70d083f099f75787879a50b92d7736ca65982a2b6a1511436208127b
